import fs, { writeFileSync } from "node:fs";
import path from "node:path";
import * as sass from "sass";
import postcss from "postcss";
import postcssModules from "postcss-modules";
import Watcher from "watcher";
import { fileURLToPath } from "node:url";
import { createHash } from "node:crypto";

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

const SRC_DIR = path.join(__dirname, "..", "src");

const WALLUST_DEFAULT = `
$wallust-background: #1C2023;
$wallust-foreground: #C7CCD1;
$wallust-cursor: #C7CCD1;

$wallust-color0: #1C2023;
$wallust-color1: #C7AE95;
$wallust-color2: #95C7AE;
$wallust-color3: #AEC795;
$wallust-color4: #AE95C7;
$wallust-color5: #C795AE;
$wallust-color6: #95AEC7;
$wallust-color7: #C7CCD1;
$wallust-color8: #747C84;
$wallust-color9: #C7AE95;
$wallust-color10: #95C7AE;
$wallust-color11: #AEC795;
$wallust-color12: #AE95C7;
$wallust-color13: #C795AE;
$wallust-color14: #95AEC7;
$wallust-color15: #F3F4F5;
`;

const args = [...process.argv];
function getFlag(flag) {
	if (!flag.startsWith("--")) {
		throw new Error(`Flag "${flag}" doesn't start with --`);
	}
	for (let i = 0; i < args.length; i++) {
		if (args[i] == flag) {
			if (i == args.length - 1) {
				throw new Error(`Option not provided for "${flag}"`);
			}
			const value = args[i + 1];
			args.splice(i, 2);
			return value;
		}
	}

	return null;
}
function getBoolean(flag) {
	if (!flag.startsWith("--")) {
		throw new Error(`Flag "${flag}" doesn't start with --`);
	}
	return args.includes(flag);
}

const noTsOutput = getBoolean("--no-ts-output");
const root = getFlag("--root") || path.resolve(__dirname, "..");

const getPlugins = (tsFileName) => [
	postcssModules({
		root,
		generateScopedName: (name, filename) => {
			const relativePath = path.relative(root, filename);
			const cleanPath = relativePath.replace(/\//g, "-").replace(/\./g, "-");

			const hash = createHash("sha1").update(relativePath).digest("hex");
			const scopedName = `${cleanPath}__${name}__${hash.substring(0, 10)}`;
			return scopedName;
		},
		getJSON: noTsOutput
			? () => {}
			: (_cssFileName, json) => {
					const content = `const styles = ${JSON.stringify(
						json,
						null,
						4,
					)};\nexport default styles;`;
					fs.writeFileSync(tsFileName, content);
				},
	}),
];

async function processFile(filePath) {
	if (path.basename(filePath).startsWith("_")) return "";

	const tsFileName =
		filePath.substring(0, filePath.length - "module.scss".length) + "style.ts";

	try {
		const result = sass.compile(filePath, { loadPaths: [SRC_DIR] });

		const { css } = await postcss(getPlugins(tsFileName)).process(result.css, {
			from: filePath,
		});

		return css;
	} catch (e) {
		console.log(`Error processing ${filePath}:`, e.message);
		return "";
	}
}

async function buildAll(outputFile, wallustFile, wallustCacheFile) {
	if (wallustCacheFile) {
		try {
			if (!wallustFile) {
				throw new Error("Wallust file not specified");
			}
			const stats = fs.statSync(wallustFile, {
				throwIfNoEntry: true,
			});
			if (!stats.isFile()) {
				throw new Error(`Wallust path isn't a file`);
			}
			writeFileSync(
				wallustCacheFile,
				`@forward ${JSON.stringify(wallustFile.replace(/\\/g, "/"))};`,
			);
			console.log("Imported Wallust values.");
		} catch (e) {
			writeFileSync(wallustCacheFile, WALLUST_DEFAULT);
			console.log("Written Wallust default values.");
		}
	}

	console.log("Compiling CSS Modules...");
	console.log("SRC_DIR:", SRC_DIR);
	console.log("ROOT:", root);

	const files = fs
		.readdirSync(SRC_DIR, { recursive: true })
		.map((f) => path.join(SRC_DIR, f));

	let globalCss = "/* Generated by styles.js */\n";

	for (const file of files) {
		if (file.endsWith(".module.scss")) {
			// console.log(file);
			const css = await processFile(file);
			globalCss += css + "\n";
		} else if (file.endsWith(".style.ts")) {
			const scssFile =
				file.substring(0, file.length - "style.ts".length) + "module.scss";
			if (!files.includes(scssFile)) {
				try {
					fs.rmSync(file);
				} catch {}
			}
		}
	}

	// if (fs.existsSync("./src/style.scss")) {
	// 	try {
	// 		const globalResult = sass.compile("./src/style.scss");
	// 		globalCss += globalResult.css;
	// 	} catch (e) {
	// 		console.error("Global SCSS error:", e.message);
	// 	}
	// }

	fs.writeFileSync(outputFile, globalCss);
	console.log(`Styles updated at ${outputFile}`);
}

const outputFile = getFlag("--output-file");
if (!outputFile) {
	throw new Error("--output-file not defined");
}
const wallustFile = getFlag("--wallust-file");
const wallustCacheFile = getFlag("--wallust-cache-file");
if (wallustFile && !wallustCacheFile) {
	throw new Error("--wallust-cache-file not defined");
}

if (getBoolean("--watch")) {
	const watcher = new Watcher(`src`, {
		recursive: true,
		ignoreInitial: true,
	});

	watcher.on("all", (_eventName, path) => {
		if (path.toLowerCase().endsWith(".style.ts")) {
			return;
		}
		buildAll(outputFile, wallustFile, wallustCacheFile);
	});

	if (wallustFile) {
		new Watcher(wallustFile, {
			recursive: false,
			ignoreInitial: true,
		}).on("all", (eventName) => {
			if (eventName == "change") {
				console.log("Wallust file changed.");
				buildAll(outputFile, wallustFile, wallustCacheFile);
			}
		});
	}
}

buildAll(outputFile, wallustFile, wallustCacheFile);
